<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Title_title</name>
   <tag></tag>
   <elementGuidId>0bba884f-3227-4d15-8905-d525056dc1d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;title&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Insert Title&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c91564ac-2790-4e47-a6e5-00ed936bcefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>29da2ce1-4fbe-43b6-b501-9ed3294fa1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Insert Title</value>
      <webElementGuid>6563fb62-f314-4e6e-b2ec-00fb67909906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d788871e-566a-400d-8666-a101cbfc00d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-form</value>
      <webElementGuid>5f171124-bdb7-4f6a-b613-e9f8cb66e1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;m-clipped&quot;]/body[@class=&quot;bg-gray-50 text-base dark:bg-gray-800 dark:text-gray-100&quot;]/div[@id=&quot;app&quot;]/div[@id=&quot;app&quot;]/div[1]/div[1]/div[@class=&quot;transition-position duration-1000 lg:pl-0&quot;]/div[@class=&quot;pt-14&quot;]/div[@class=&quot;vfm vfm--inset vfm--fixed vfm--prevent-none&quot;]/div[@class=&quot;vfm__container vfm--absolute vfm--inset vfm--outline-none base-modal&quot;]/div[@class=&quot;vfm__content add-modal bg-white transition-colors duration-1000 vfm--prevent-auto&quot;]/div[@class=&quot;modal-content&quot;]/form[@class=&quot;w-full h-full&quot;]/div[@class=&quot;flex flex-wrap mx-3 mb-2&quot;]/div[@class=&quot;mb-6 last:mb-0 w-full md:ml-2 md:mr-2 mb-2 md:mb-0&quot;]/div[1]/div[@class=&quot;relative form-comp&quot;]/input[@class=&quot;input-form&quot;]</value>
      <webElementGuid>2933f88d-4ced-49d5-a91a-6aa5d1f8cb0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='title']</value>
      <webElementGuid>518cf6a3-f9ab-4876-b1d8-77177c01f15a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/div[3]/div[2]/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>87e967c5-6919-40db-acdb-089952e6de8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>50f0d753-763c-4676-bd3e-a1609445b480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'title' and @placeholder = 'Insert Title' and @type = 'text']</value>
      <webElementGuid>1ae5b2fe-497a-4c1c-9a44-59b62117e586</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
