<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Show Time_date</name>
   <tag></tag>
   <elementGuidId>83e8fed7-77cc-412f-9002-2195f0952ed2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;date&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;date&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb02d619-840b-4866-b740-e259cb117795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>be02e87c-58f1-42bf-bf68-1fc7c92933dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dp__pointer dp__input_readonly dp__input dp__input_icon_pad dp__input_focus dp__input_reg</value>
      <webElementGuid>e9dfee98-db91-4f53-94a8-6e74a3d19fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>a6399c27-32cd-4f5a-acc9-1f7fbe10aa5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>56d72064-8479-41b6-a5a6-ab472c2969a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;m-clipped&quot;]/body[@class=&quot;bg-gray-50 text-base dark:bg-gray-800 dark:text-gray-100&quot;]/div[@id=&quot;app&quot;]/div[@id=&quot;app&quot;]/div[1]/div[1]/div[@class=&quot;transition-position duration-1000 lg:pl-0&quot;]/div[@class=&quot;pt-14&quot;]/div[@class=&quot;vfm vfm--inset vfm--fixed vfm--prevent-none&quot;]/div[@class=&quot;vfm__container vfm--absolute vfm--inset vfm--outline-none base-modal&quot;]/div[@class=&quot;vfm__content add-modal bg-white transition-colors duration-1000 vfm--prevent-auto&quot;]/div[@class=&quot;modal-content&quot;]/form[@class=&quot;w-full h-full&quot;]/div[@class=&quot;flex flex-wrap mx-3 mb-2&quot;]/div[@class=&quot;mb-6 last:mb-0 w-full md:ml-2 md:mr-2 mb-2 md:mb-0&quot;]/div[1]/div[@class=&quot;dp__main dp__theme_light&quot;]/div[1]/div[@class=&quot;dp__input_wrap&quot;]/input[@class=&quot;dp__pointer dp__input_readonly dp__input dp__input_icon_pad dp__input_focus dp__input_reg&quot;]</value>
      <webElementGuid>9c7c94f4-63fc-4f3c-a3ae-692927971798</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='date']</value>
      <webElementGuid>1d9fe51b-2644-4864-b7ed-105200de40b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/div[3]/div[2]/div/div[2]/form/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>de39d395-7449-4f22-a97b-780f51ed1ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/input</value>
      <webElementGuid>e235fb7b-6c5c-407d-b995-2207b447ef67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'date']</value>
      <webElementGuid>55068b35-e37d-44a3-b5d1-03a4080b0fea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
